# ==========================================================
# 1. DATASET DE TREINAMENTO 
# ==========================================================
dataset:
  #image_transforms:
  #  enable: true
  #  max_num_transforms: 3
  #  tfs:
  #    ColorJitter:
  #      type: ColorJitter
  #      weight: 1.0
  #      kwargs:
  #        brightness: [0.8, 1.2]
  #        contrast: [0.8, 1.2]
  #        saturation: [0.5, 1.5]
  #        hue: [-0.05, 0.05]
  #    # BLINDAGEM 1: Translação e Rotação Aleatória
  #    # Desloca a câmera 5% pros lados e gira 5 graus a cada frame. 
  #    # Isso impede a IA de decorar a coordenada exata da xícara na tela!
  #    RandomAffine:
  #      type: RandomAffine
  #      weight: 1.0
  #      kwargs:
 #         degrees: [-5.0, 5.0]
 #         translate: [0.05, 0.05]

  repo_id: Mrwlker/pick_up_the_cup3
  root: meu_dataset/pick_up_the_cup3
  episodes: [1, 2, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 16, 17, 18, 20, 21, 22, 23]

# ==========================================================
# 2. DATASET DE VALIDAÇÃO
# ==========================================================
val_dataset:
  repo_id: Mrwlker/pick_up_the_cup3
  root: meu_dataset/pick_up_the_cup3
  episodes: [3, 8, 15, 19]

# ==========================================================
# 3. ARQUITETURA DA IA (Action Chunking with Transformers)
# ==========================================================
policy:
  type: actdepth
  repo_id: Mrwlker/pick_up_the_cup_depth
  push_to_hub: false
  
  input_features:
    observation.images.head_camera:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.head_camera_depth:
      type: VISUAL
      shape: [3, 480, 640]
      
    # CORREÇÃO: Mantido em 28 para bater com o Parquet!
    observation.state:
      type: STATE
      shape: [28] 
      
    # Pressões Dex3
    observation.left_hand_pressure:
      type: STATE
      shape: [33]
    observation.right_hand_pressure:
      type: STATE
      shape: [33]
      
  output_features:
    action:
      type: ACTION
      shape: [28] # CORREÇÃO: Mantido em 28 para bater com o Parquet!

  chunk_size: 100
  n_action_steps: 100
  n_obs_steps: 1
  use_amp: true 
  
  # BLINDAGEM 2: Regularização do Transformer
  dropout: 0.2              # Padrão é 0.1. Aumentamos para forçar a rede a ignorar ruídos.
  optimizer_weight_decay: 1e-3 # Pune a rede se ela der pesos gigantescos para um único pixel.
  kl_weight: 15.0           # Força a distribuição do VAE a ficar mais suave e generalista.

# ==========================================================
# 4. CONFIGURAÇÕES DE TREINAMENTO (Para 2x A100)
# ==========================================================
output_dir: "train_output/pick_up_the_cup_depth"
steps: 5000          

# BLINDAGEM 3: Batch Size Dinâmico
# Como usaremos 2 GPUs, o LeRobot multiplica esse número por 2.
# 32 x 2 GPUs = 64 (Tamanho perfeito para aprender sem decorar o dataset de 4k frames)
batch_size: 4       
num_workers: 2
log_freq: 200         
save_freq: 1000      
save_checkpoint: true

# ==========================================================
# 5. AVALIAÇÃO E LOGS
# ==========================================================
eval_freq: 200       

wandb:
  enable: false       
  project: prometheus_g1