# ==========================================================
# 1. DATASET DE TREINAMENTO 
# ==========================================================
dataset:
  image_transforms:
    enable: true
    max_num_transforms: 1
    tfs:
      ColorJitter:
        type: ColorJitter
        weight: 1.0
        kwargs:
          brightness: [0.8, 1.2]
          contrast: [0.8, 1.2]
          saturation: [0.5, 1.5]
          hue: [-0.05, 0.05]

  repo_id: Mrwlker/pick_up_the_cup_2026-04-30
  root: meu_dataset/pick_up_the_cup_2026-04-30
  episodes: [1, 2, 3, 4, 5, 6, 8, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21]

# ==========================================================
# 2. DATASET DE VALIDAÇÃO
# ==========================================================
val_dataset:
  repo_id: Mrwlker/pick_up_the_cup_2026-04-30
  root: meu_dataset/pick_up_the_cup_2026-04-30
  episodes: [7, 9, 18, 19]

# ==========================================================
# 3. ARQUITETURA DA IA (Action Chunking with Transformers)
# ==========================================================
policy:
  type: actdepth
  repo_id: Mrwlker/pick_up_the_cup_nodepth
  push_to_hub: false
  
  input_features:
    observation.images.head_camera:
      type: VISUAL
      shape: [3, 480, 640]
      
    # ❌ TESTE BASELINE: Desligando a Nuvem de Pontos 3D
    #observation.images.head_camera_depth:
    #  type: VISUAL
    #  shape: [3, 480, 640]
      
    observation.state:
      type: STATE
      shape: [28] 
      
    # ❌ TESTE BASELINE: Desligando a Percepção Tátil
    #observation.left_hand_pressure:
    #  type: STATE
    #  shape: [33]
    #observation.right_hand_pressure:
    #  type: STATE
    #  shape: [33]
      
  output_features:
    action:
      type: ACTION
      shape: [28]

  chunk_size: 100
  n_action_steps: 100
  n_obs_steps: 1
  use_amp: true 
  
  # BLINDAGENS CONTRA OVERFITTING (MANTIDAS!)
  dropout: 0.2                 
  optimizer_weight_decay: 1e-3 
  kl_weight: 1.0              

# ==========================================================
# 4. CONFIGURAÇÕES DE TREINAMENTO
# ==========================================================
output_dir: "train_output/pick_up_the_cup_nodepth-260511"
steps: 100000       

# O Batch Size menor (32) força a rede a generalizar.
batch_size: 256       
num_workers: 10
log_freq: 200         
save_freq: 10000      
save_checkpoint: true

# ==========================================================
# 5. AVALIAÇÃO E LOGS
# ==========================================================
eval_freq: 200       

wandb:
  enable: true       
  project: prometheus_g1