robot:
  type: unitree_g1_dex3
  control_mode: "upper_body"

teleop:
  type: xr_g1_arm
  zmq: true
  input_mode: "hand"
  display_mode: "ego"
  ee_type: "dex3"

dataset:
  repo_id: Mrwlker/get_kettle
  root: "meu_dataset/get_kettle"
  push_to_hub: true
  single_task: "get kettle"
  vcodec: "h264"

play_sounds: false