robot:
  type: unitree_g1_dex3
  control_mode: "upper_body"

teleop:
  type: xr_g1_arm
  zmq: true
  input_mode: "controller"
  display_mode: "ego"
  ee_type: "dex3"

dataset:
  repo_id: Mrwlker/pick_up_the_cup_2026-04-30
  root: "meu_dataset/pick_up_the_cup_2026-04-30"
  push_to_hub: true
  single_task: "pick up the cup"
  vcodec: "h264"

play_sounds: false