robot:
  type: unitree_g1_dex3

teleop:
  type: xr_g1_arm
  zmq: true
  input_mode: "hand"
  display_mode: "ego"
  ee_type: "dex3"

dataset:
  repo_id: Mrwlker/get_the_kettle
  root: "meu_dataset/get_the_kettle"
  push_to_hub: false
  single_task: "get the kettle"
  vcodec: "h264"

play_sounds: false