robot:
  type: unitree_g1_dex3
  control_mode: "upper_body"

teleop:
  type: keyboard_g1_arm

dataset:
  repo_id: Mrwlker/teste3
  root: "meu_dataset/teste3"
  push_to_hub: true
  single_task: "teste3"
  vcodec: "h264"


play_sounds: false