robot:
  type: unitree_g1_dex3

teleop:
  type: keyboard_g1_arm

dataset:
  repo_id: Mrwlker/teste1
  root: "meu_dataset/teste1"
  push_to_hub: false
  single_task: "teste1"
  vcodec: "h264"

play_sounds: false