robot:
  type: unitree_g1_dex3
  is_simulation: true

teleop:
  type: keyboard_g1_arm

dataset:
  repo_id: Mrwlker/g1_pick_kettle_custom
  root: "meu_dataset"
  push_to_hub: false
  single_task: "Pick up arm"
  vcodec: "h264"

play_sounds: false